export const prerender = false;

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const GITHUB_REPO = process.env.GITHUB_REPO || '0xnewbiewhermes/cryptosynth';
const GITHUB_FILE_PATH = 'src/data/airdrops.json';
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD;

function checkAuth(request: Request): boolean {
  const authHeader = request.headers.get('Authorization');
  if (!authHeader || !authHeader.startsWith('Bearer ')) return false;
  const token = authHeader.slice(7);
  // Simple check: token was generated by login endpoint
  try {
    const decoded = atob(token);
    return decoded.startsWith('admin:');
  } catch {
    return false;
  }
}

// GET — Load airdrops data from GitHub
export async function GET({ request }: { request: Request }) {
  if (!checkAuth(request)) {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), {
      status: 401,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  if (!GITHUB_TOKEN) {
    return new Response(JSON.stringify({ error: 'Server not configured (GITHUB_TOKEN missing)' }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  try {
    const res = await fetch(
      `https://api.github.com/repos/${GITHUB_REPO}/contents/${GITHUB_FILE_PATH}`,
      {
        headers: {
          'Authorization': `token ${GITHUB_TOKEN}`,
          'Accept': 'application/vnd.github.v3+json',
          'User-Agent': 'CryptoSynth-Admin',
        },
      }
    );

    if (!res.ok) {
      return new Response(JSON.stringify({ error: 'GitHub API error: ' + res.status }), {
        status: 502,
        headers: { 'Content-Type': 'application/json' },
      });
    }

    const fileData = await res.json();
    const content = atob(fileData.content.replace(/\n/g, ''));
    const data = JSON.parse(content);

    return new Response(JSON.stringify({ data, sha: fileData.sha }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    });
  } catch (err: any) {
    return new Response(JSON.stringify({ error: 'Failed to load data: ' + err.message }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }
}

// POST — Save airdrops data to GitHub
export async function POST({ request }: { request: Request }) {
  if (!checkAuth(request)) {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), {
      status: 401,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  if (!GITHUB_TOKEN) {
    return new Response(JSON.stringify({ error: 'Server not configured (GITHUB_TOKEN missing)' }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  try {
    const body = await request.json();
    const { data, sha, message } = body;

    if (!data || !sha) {
      return new Response(JSON.stringify({ error: 'Missing data or sha' }), {
        status: 400,
        headers: { 'Content-Type': 'application/json' },
      });
    }

    // Format JSON with 2-space indent (matching the repo format)
    const jsonContent = JSON.stringify(data, null, 2) + '\n';
    const encodedContent = btoa(unescape(encodeURIComponent(jsonContent)));

    const commitMessage = message || `admin: update airdrops data (${new Date().toISOString().slice(0, 10)})`;

    const res = await fetch(
      `https://api.github.com/repos/${GITHUB_REPO}/contents/${GITHUB_FILE_PATH}`,
      {
        method: 'PUT',
        headers: {
          'Authorization': `token ${GITHUB_TOKEN}`,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json',
          'User-Agent': 'CryptoSynth-Admin',
        },
        body: JSON.stringify({
          message: commitMessage,
          content: encodedContent,
          sha: sha,
        }),
      }
    );

    if (!res.ok) {
      const errBody = await res.json();
      return new Response(JSON.stringify({ error: 'GitHub API error: ' + (errBody.message || res.status) }), {
        status: 502,
        headers: { 'Content-Type': 'application/json' },
      });
    }

    const result = await res.json();

    return new Response(JSON.stringify({
      success: true,
      commitSha: result.commit.sha,
      newFileSha: result.content.sha,
      message: 'Data tersimpan! Vercel akan auto-deploy dalam ~30 detik.',
    }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    });
  } catch (err: any) {
    return new Response(JSON.stringify({ error: 'Failed to save: ' + err.message }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }
}
